"""cripto tabela

Revision ID: 16c6a066ae09
Revises: 8e7c41652aee
Create Date: 2025-10-25 17:07:58.448014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "16c6a066ae09"
down_revision: Union[str, Sequence[str], None] = "8e7c41652aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("aes_key", sa.String(length=512), nullable=False),
        sa.Column("iv", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column(
        "users", "cpf", existing_type=sa.VARCHAR(length=11), type_=sa.String(length=255), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "cpf", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=11), existing_nullable=False
    )
    op.drop_table("user_keys")
    # ### end Alembic commands ###
