"""update termos

Revision ID: 1f28c8673862
Revises: 16c6a066ae09
Create Date: 2025-10-25 22:08:25.506966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1f28c8673862"
down_revision: Union[str, Sequence[str], None] = "16c6a066ae09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_user_terms", "terms_acceptance", ["user_id", "terms_id"])
    op.add_column("terms_of_use", sa.Column("type", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("terms_of_use", "type")
    op.drop_constraint("uix_user_terms", "terms_acceptance", type_="unique")
    # ### end Alembic commands ###
