"""TermsOfUse expired_at

Revision ID: 487661798840
Revises: 3e545bccb0fb
Create Date: 2025-11-25 15:34:58.097825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "487661798840"
down_revision: Union[str, Sequence[str], None] = "3e545bccb0fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("terms_of_use", sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("terms_of_use", "expired_at")
    # ### end Alembic commands ###
