"""expired_at in TermsOfUse

Revision ID: 7db4deb60915
Revises: 1f28c8673862
Create Date: 2025-11-18 22:21:25.329421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7db4deb60915"
down_revision: Union[str, Sequence[str], None] = "1f28c8673862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("terms_of_use", sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("terms_of_use", "expired_at")
    # ### end Alembic commands ###
